### ISSUE TITLE
[Feature Request]: Redesign EatMyURL Flutter UI

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/EatMyURL#12]
### Description

We are looking to redesign our app UI. Intreated guys, please contact us on discord to know about the workflow. Issues can be raised accordingly. Find the UI design below. 

|<img src="https://cdn.discordapp.com/attachments/701086382407549019/949252650912866304/1.png" width="100%" > | <img src="https://cdn.discordapp.com/attachments/701086382407549019/949253255957995530/2.png" width="100%">|<img src="https://cdn.discordapp.com/attachments/701086382407549019/949252651386802196/3.png" width="100%">| <img src="https://cdn.discordapp.com/attachments/701086382407549019/949252650694750228/4.png" width="100%">|
|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|

### Domain

Client - (Flutter)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by slothtae** [comment]
Hi, I am Karan Boro, a contributor to GSSoC'22. I would like to work on this issue.

**Comment by vigneshshettyin** [comment]
Hey, @slothtae assigning this issue to you. For any queries pls contact @data-charya

**Comment by slothtae** [comment]
> Hey, @slothtae assigning this issue to you. For any queries pls contact @data-charya

Thank you

**Comment by bh-divyansh** [comment]
Hey @vigneshshettyin, I am also a GSSOC '22 contributor. I would also like to work on this Issue. Can you please assign it to me also?

**Comment by vigneshshettyin** [comment]
> Hey @vigneshshettyin, I am also a GSSOC '22 contributor. I would also like to work on this Issue. Can you please assign it to me also?

This issue has already been assigned to @slothtae. Please raise any new issue for any new improvements

**Comment by vigneshshettyin** [comment]
> Hey @vigneshshettyin, I am also a GSSOC '22 contributor. I would also like to work on this Issue. Can you please assign it to me also?

Hey, @bh-divyansh are you interested in working on this issue!

**Comment by bh-divyansh** [comment]
> > Hey @vigneshshettyin, I am also a GSSOC '22 contributor. I would also like to work on this Issue. Can you please assign it to me also?
> 
> Hey, @bh-divyansh are you interested in working on this issue!

Hey @vigneshshettyin , Sure! I would love to work on this issue.

**Comment by vigneshshettyin** [comment]
Hi, @bh-divyansh assigning this issue to you!

**Comment by anushkashelke** [comment]
Can you assign this task to me?

**Comment by vigneshshettyin** [comment]
@anushkashelke Yes!

**Comment by anushkashelke** [comment]
Yes I am ready to do the task...Also do I have to do the same UI as shown
in the task?

**Comment by vigneshshettyin** [comment]
Nope, that is just for reference @anushkashelke 

Find the link to api docs https://eurl.vigneshcodes.in/api-docs/
