### ISSUE TITLE
Validate access and refresh tokens

### ISSUE THREAD

**Issue by AdnanMuzavor** [vigneshshettyin/EatMyURL#16]
### Description

Refresh and valid tokens are sent to user.
To validate following can be done.
->First check if access is still valid , if valid no issue
->If invalid, check if refresh is valid(It should be same as in DB and valid as per jwt.verify)
->If refresh is valid access and refresh both will be updated in DB to new valid tokens
->If refresh too is invalid, user will be asked to login again("Should be handled at frontend, as per response sent from backend).

### Domain

Server - (Express)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vigneshshettyin** [comment]
Hey, @AdnanMuzavor assigning this issue to you!
