### ISSUE TITLE
[Feature Request]: Link URLs with user who posted them

### ISSUE THREAD

**Issue by AdnanMuzavor** [vigneshshettyin/EatMyURL#18]
### Description

When ever user posts a URL first "/token" route will be called to authenticate him(from frontend) and if user is authorised, along with URL to be shorten user id stored in userData will be sent. Hence when it's saved in DB userData will be linked to it through user id.

Again in "/getallurls" route we can give user in req body and with help of this user (user _id) we can filter and show only those links posted by user. Also user data in URLS will be populated showing all user details.

### Domain

Server - (Express)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vigneshshettyin** [comment]
Okay, @AdnanMuzavor assigning this issue to you.
