### ISSUE TITLE
Configuration the server for calls on Flutter App

### ISSUE THREAD

**Issue by seifibrahim32** [vigneshshettyin/EatMyURL#25]
I have issues for the application , I need to make a call on the server and I cant handle it

**Comment by seifibrahim32** [comment]
I need to make a meeting with mentors please

**Comment by seifibrahim32** [comment]
I need to parse JSON with Dio package or HTTP package

**Comment by vigneshshettyin** [comment]
@data-charya please look into this

**Comment by seifibrahim32** [comment]
?? Can we talk on Discord or WhatsApp

**Comment by seifibrahim32** [comment]
@data-charya

**Comment by seifibrahim32** [comment]
Can I contribute to this project after GSSoC? and I can right now still contribute?

**Comment by seifibrahim32** [comment]
@vigneshshettyin
