### ISSUE TITLE
[Feature Request]: Create Login/Register flow in Next using NextAuth

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/EatMyURL#29]
### Description

Requirements
Data to be collected Name, Email and Password for Register page

### Domain

Client - (React)

### Code of Conduct

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vigneshshettyin** [comment]
Separate login and register page is not required use Google Auth
 
Ref : https://next-auth.js.org/ 

@VijeshVS

**Comment by VijeshVS** [comment]
next-auth is limited to next-js

**Comment by vigneshshettyin** [comment]
> next-auth is limited to next-js

IK, We will creating a Next app

**Comment by vigneshshettyin** [comment]
Created a feature issue for the same (#36 ) 

@VijeshVS
