### ISSUE TITLE
[Feature Request]: Setup Next app

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/EatMyURL#36]
### Description

Description
Setup Next app with ts with required configs and linting with shadcn/ui (https://ui.shadcn.com/)

### Domain

Client - (React)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vigneshshettyin** [comment]
![image](https://github.com/vigneshshettyin/EatMyURL/assets/77713888/4fa64ff3-b696-46eb-995c-ae181cf0c0b2)

Fix above issues @VijeshVS

**Comment by VijeshVS** [comment]
Oh !! Got the problem. Mistake from my end. I'll fix it asap
