### ISSUE TITLE
Setting up Axios also single instance structure to call eatmyurl API

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/EatMyURL#7]

**Comment by VRAJ9799** [comment]
Hi Vignesh I am a participant in GSSOC and would like to work on this.
Can you please describe little bit in detail.
@vigneshshettyin

**Comment by vigneshshettyin** [comment]
Hey, @VRAJ9799 we have actually implemented this. Sorry, we forgot to close the pull request. I recommend you go through the live-hosted URL and suggest some UI improvements or new features. 
Live Link: https://app.eurl.tech
