### ISSUE TITLE
Optimizing UI elements and avoiding redundant components.

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/EatMyURL#8]
Convert application into fully component-based avoid redundant coding practices. 

Refer to https://reactjs.org/docs/react-component.html

**Comment by HarshKumarChoudary** [comment]
Could you please assign this issue to me.

**Comment by vigneshshettyin** [comment]
Hey, @HarshKumarChoudary thanks for raising an issue. Could you list all changes which you want to work on? 
Live Link: https://app.eurl.tech
Github (React v2): https://github.com/vigneshshettyin/EatMyURL/tree/main/Client%20-%20React/v2
As we are migrating our API to AWS Serverless it's currently under testing.
