### ISSUE TITLE
Features to be implemented

### ISSUE THREAD

**Issue by VijeshVS** [vigneshshettyin/EatMyURL#87]
- Custom ShortCode Support 
Eg: https://eurl.vshetty.dev/hello

- Enable Private ShortCodes

- Edit ShortCode and Title
Request body : {
title: string,
shortcode: string
}

- Click Analytics with weekly engagements, last 7 days, locations, devices, OS, browsers 

- An endpoint which confirms if user has at least one link create and the short link has been hit at least once
response body : {
hasCreatedLink : Boolean,
hasClickedLink : Boolean
}

**Comment by vigneshshettyin** [comment]
Custom ShortCode Support
Eg: https://eurl.vshetty.dev/hello

Enable Private ShortCodes

Edit ShortCode and Title
Request body : {
title: string,
shortcode: string
}

Click Analytics with weekly engagements, last 7 days, locations, devices, OS, browsers

// this is completed by @vigneshshettyin & @VijeshVS
